### PR TITLE
Guide to task apps

### PR DESCRIPTION
**Pull request by judu**
## Describe your PR

Get a bit more in detail to the process of configuring and running a Task application.

## Checklist

- [ ] My PR is related to an opened issue : #
- [x] I've read the [contributing guidelines](/CleverCloud/documentation/blob/main/CONTRIBUTING.md)

## Reviewers
@davlgd

### CODE REVIEW

**Comment by judu** [comment]
@davlgd to complete the changelog a bit, here’s the Task doc that was sleeping in a branch!

**Comment by juliamrch** [comment]
The guides section is mostly dedicated to frameworks and well-known Open Source tools. This page should be in `/documentation`, which can take small "how to" as well

**Comment by davlgd** [comment]
> @davlgd to complete the changelog a bit, here’s the Task doc that was sleeping in a branch!

Thanks, I'll take a look at it 🙏

**Comment by juliamrch** [comment]
Doing some tests to check why the app isn't deploying, don't panic.

**Comment by juliamrch** [comment]
There you go, pipeline fixed.

**Comment by juliamrch** [comment]
@davlgd any updates on this?

**Comment by juliamrch** [comment]
PR is 31 days old. Will likely be closed by the end of the week if there's no progress on it.

**Pull request closed without merging**
