### PR TITLE
Undocument deprecated servlet containers

### PR DESCRIPTION
**Pull request by judu**
## Describe your PR

To begin deprecate/remove old and unused servlet containers, I removed them from the documentation.

### CODE REVIEW

**Comment by judu** [comment]
Oops, removed too much

**Comment by davlgd** [comment]
I'll add a changelog entry to this PR, so they will be merged together. LGTY ?

**Comment by judu** [comment]
> I'll add a changelog entry to this PR, so they will be merged together. LGTY ?

Feel free!

**Review by juliamrch — APPROVED** [review]
noice

**Comment by davlgd** [comment]
@judu can you check if it's ok for you ?

**Review by davlgd — APPROVED** [review]
LGTM

**Pull request merged**
