### PR TITLE
Newrelic browser monitoring warn

### PR DESCRIPTION
**Pull request by cnivolle**
## Checklist

- [x] My PR is related to an opened issue : #10

## Pull request type
Doc update.

Please check the type of change your PR introduces:

- [x] Documentation content changes
- [ ] Bugfix on the site
- [ ] Build related changes
- [ ] Other (please describe):
      
## Description
Adding a callout to warn about New Relic's auto-insertion of JavaScript, and explain how to disable it.

### Why is this needed?
An issue was opened: #10.

## Reviewes
_Who should review these changes?_ @juliamrch

### CODE REVIEW

**Review by juliamrch — DISMISSED** [review]
We can fix the link color after merging.

**Comment by juliamrch** [comment]
Last commit containing css update has been successfully deployed on Clever Cloud but for some reason the job is showing a timeout.

**Comment by cnivolle** [comment]
@juliamrch That's perfect.

**Review by cnivolle — COMMENTED** [review]
All good for me.

**Review by juliamrch — APPROVED** [review]

**Pull request merged**
