### PR TITLE
Fixing Jetty URLs and adding EOL status

### PR DESCRIPTION
**Pull request by joakime**
## Describe your PR

Jetty versions below Jetty 12 are considered EOL now.

Jetty 6 predates the move to Eclipse, and is not part of the `org.eclipse.jetty` namespace.

Jetty website moved from eclipse.org/jetty to jetty.org

Jetty website at codehaus.org is long since dead. (All links to any project once hosted at codehaus.org are dead)

Documentation for Jetty 7 and Jetty 8 does not exist online, as they are very out of date and EOL.

## Checklist

- [X] My PR is related to an opened issue : # (cannot open issue reporting a bug in documentation, only can open issue for new content)
- [X] I've read the [contributing guidelines](/CleverCloud/documentation/blob/main/CONTRIBUTING.md)

## Reviewers
_Who should review these changes?_ @

### CODE REVIEW

**Comment by joakime** [comment]
The table of server containers should be updated to reflect if they are EOL or not.  I flagged the Jetty ones, but you'll have to address the other containers.

Any container no longer being supported by the maintainers should not be used on the open internet as it does not contain fixes for behaviors that the industry as a whole have adopted. (eg: TLS changes, Cookie changes, HTTP/1.x spec changes, Browser changes, etc)

If you insist on keeping these EOL container versions listed in your documentation, then list them as EOL (should not be used anymore, upgrade to a supported version as soon as possible)

**Comment by juliamrch** [comment]
Hi @joakime, thank you so much for taking the time to contribute to our doc!

We're currently under a big rework on our image creation and maintenance on Clever Cloud, I'll assign this to the relevant people to get their input on this. For now, I've added the version history link in the table, so users know exactly the state of the version containers. https://jetty.org/download.html#version-history

Some customers run legacy code and need antique containers as they upgrade it, so some are still operating 🧟‍♀️🧟‍♂️

I'll let the team managing the Java image to have the final word on the EOL tag on our doc, since they are the ones that will write and update it.

**Comment by joakime** [comment]
> Some customers run legacy code and need antique containers as they upgrade it, so some are still operating

That's why Jetty 12 has a `ee8` environment.  
Even running Jetty 12, you can still use the old / ancient container behaviors (like the venerable `javax.servlet` namespace) by using that environment.

**Review by s0dyy — DISMISSED** [review]

**Comment by juliamrch** [comment]
Some issues with GH runners not triggering the deploy, but the latest review app works fine. Merging.

**Pull request merged**
