### PR TITLE
Add instructions to use FIDO/U2F compatible SSH keys

### LINKED ISSUE #44: Document 2FA SSH key
@Keruspe [pointed out](https://twitter.com/Keruspe/status/1392370389611859968?s=20) that we can use ed25519-sk and ecdsa-sk keys. I think we should document it.

### PR DESCRIPTION
**Pull request by davlgd**
## Checklist

- [x] My PR is related to an opened issue : fix #44

### CODE REVIEW

**Review by juliamrch — CHANGES_REQUESTED** [review]
Looks like this branch wasn't up to date, because this is the file currently deployed with steps shot codes and updated format: https://developers.clever-cloud.com/doc/account/ssh-keys-management/#how-to-add-your-ssh-key-on-clever-cloud

**Comment by juliamrch** [comment]
Yo @CleverAkanoa could you confirm this new part of the doc is accurate? http://clever-doc-review-davlgd-ssh-fido-keys-pr-131.cleverapps.io/doc/account/ssh-keys-management/#add-a-fidou2f-ssh-key

**Comment by CleverAkanoa** [comment]
It seems there are some concerns on the ecdsa key length. 
https://wiki.archlinux.org/title/SSH_keys#ECDSA

The preferred method is 

```
brew install libfido2
brew install openssh
ssh-keygen -t ed25519-sk -C "my ed25519-sk key"
```
https://stackoverflow.com/a/77539417

But I haven't mac device to test it.

**Review by CleverAkanoa — APPROVED** [review]

**Comment by davlgd** [comment]
I didn't find a simple way for `ed25519-sk` to work on my machine with FIDO2/U2F keys, but I'll monitor this to update when such a "bug" is fixed from Apple or OpenSSH

**Comment by juliamrch** [comment]
> It seems there are some concerns on the ecdsa key length. https://wiki.archlinux.org/title/SSH_keys#ECDSA

Yep. Ultimately the users will make their mind and choose the format. Not sure it's worth mentioning how the NSA is hurting the Cryptography Standard, seems a lil too deep for this doc. 
 
> The preferred method is
> 
> ```
> brew install libfido2
> brew install openssh
> ssh-keygen -t ed25519-sk -C "my ed25519-sk key"
> ```
> 
> https://stackoverflow.com/a/77539417
> 
> But I haven't mac device to test it.

I have a Mac but already have libfido2 running on it, so who knows. I don't think many people doing development wouldn't have it installed anyway, it's required for running mysql and other stuff.

**Pull request merged**
