### PR TITLE
Update Hugo deploy script

### PR DESCRIPTION
**Pull request by davlgd**
- Add shebang
- Add vars at the begining of the script
- Clean archive after download
- Use folder in $PATH

### CODE REVIEW

**Comment by juliamrch** [comment]
Why is this needed?

**Comment by davlgd** [comment]
> Why is this needed?

It's not "needed", I just iterated on the original script with elements mentioned in the commit message.

**Review by cnivolle — COMMENTED** [review]
Hi @davlgd and thank your for your submission,

Regarding the pull [request template](https://github.com/CleverCloud/documentation/blob/main/.github/pull_request_template.md), this PR is not matching any the following changes : 
* This is not a documentation content changes
* This is not fixing a bug on the site
* This doesn't change the build process, as it is the same Hugo build command

This add complexity to the actual build change, leading to fewer people to understand the build process. Especially because this PR add local variable to the file, along with Clever Cloud environment variables. This might be confusing for future maintenance. The simpler the better.

**Review by juliamrch — COMMENTED** [review]
See comment [here](https://github.com/CleverCloud/documentation/pull/106#pullrequestreview-1793158287)

**Pull request closed without merging**
